### ISSUE TITLE
Error when running Aspire in Debug mode

### ISSUE THREAD

**Issue by KazysNoobiys** [JetBrains/aspire-plugin#266]
When trying to run the Aspire project in Debug mode, the following error occurs:

```
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.IO.Pipelines.StreamPipeReader.<ReadInternalAsync>g__Core|40_0(StreamPipeReader reader, Nullable`1 minimumSize, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Aspire.Hosting.Dcp.DcpHostService.LogSocketOutputAsync(Socket socket, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 323
```

This error only happens in Debug mode.
When running the project without debugging, everything works fine.
Additionally, the project runs perfectly in both Debug and non-Debug modes in Visual Studio 2022.

**Comment by KazysNoobiys** [comment]
The issue can be closed. The problem was solved by deleting the .idea folder from the project root

**Comment by KazysNoobiys** [comment]
The issue can be closed. The problem was solved by deleting the .idea folder from the project root
